package com.bank.bian.contactrouting;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Contact Routing
 *
 * Business Area:      Sales and Service
 * Business Domain:    Channels
 * Functional Pattern: Process
 * Asset Type:         Contact Routing Record
 * Control Record:     Contact Routing Record Procedure
 *
 * Generated by the bian-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Contact Routing — BIAN Semantic API")
                .description("Service Domain 'Contact Routing' (Process pattern) "
                        + "operating on the 'Contact Routing Record Procedure' control record.")
                .version("0.1.0"));
    }
}
